/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Huy
 */
public class PnlChuyenTau extends javax.swing.JPanel {

    /**
     * Creates new form PnlChuyenTau
     */
    public PnlChuyenTau() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlLeft = new javax.swing.JPanel();
        pnlRightTop = new javax.swing.JPanel();
        boxGaDi = new javax.swing.JPanel();
        lblGaDi = new javax.swing.JLabel();
        cboGaDi = new javax.swing.JComboBox<>();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        boxGaDen = new javax.swing.JPanel();
        lblGaDen = new javax.swing.JLabel();
        cboGaDen = new javax.swing.JComboBox<>();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        boxTau = new javax.swing.JPanel();
        lblTau = new javax.swing.JLabel();
        cboTau = new javax.swing.JComboBox<>();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        boxNgayDi = new javax.swing.JPanel();
        lblNgayDi = new javax.swing.JLabel();
        txtNgayDi = new javax.swing.JTextField();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        boxGioDi = new javax.swing.JPanel();
        lblGioDi = new javax.swing.JLabel();
        txtGioDi = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        boxNgayDen = new javax.swing.JPanel();
        lblNgayDen = new javax.swing.JLabel();
        txtNgayDen = new javax.swing.JTextField();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        boxGioDen = new javax.swing.JPanel();
        lblGioDen = new javax.swing.JLabel();
        txtGioDen = new javax.swing.JTextField();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        boxChucNang = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        pnlRight = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChuyenTau = new javax.swing.JTable();
        pnlRightNorth = new javax.swing.JPanel();
        lblTimMaChuyen = new javax.swing.JLabel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        txtTimMaChuyen = new javax.swing.JTextField();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        btnTraCuuTheoMa = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1920, 800));
        setLayout(new java.awt.BorderLayout());

        pnlTop.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlTop.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pnlTop.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Quản lý chuyến tàu");
        pnlTop.add(lblTitle, java.awt.BorderLayout.CENTER);

        add(pnlTop, java.awt.BorderLayout.NORTH);

        pnlLeft.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chuyến tàu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        pnlLeft.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pnlLeft.setPreferredSize(new java.awt.Dimension(300, 182));
        pnlLeft.setLayout(new java.awt.BorderLayout());

        pnlRightTop.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlRightTop.setLayout(new javax.swing.BoxLayout(pnlRightTop, javax.swing.BoxLayout.Y_AXIS));

        boxGaDi.setLayout(new javax.swing.BoxLayout(boxGaDi, javax.swing.BoxLayout.X_AXIS));

        lblGaDi.setText("Ga đi");
        lblGaDi.setPreferredSize(new java.awt.Dimension(80, 0));
        boxGaDi.add(lblGaDi);

        cboGaDi.setEditable(true);
        cboGaDi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxGaDi.add(cboGaDi);

        pnlRightTop.add(boxGaDi);
        pnlRightTop.add(filler1);

        boxGaDen.setLayout(new javax.swing.BoxLayout(boxGaDen, javax.swing.BoxLayout.X_AXIS));

        lblGaDen.setText("Ga đến");
        lblGaDen.setPreferredSize(new java.awt.Dimension(80, 0));
        boxGaDen.add(lblGaDen);

        cboGaDen.setEditable(true);
        cboGaDen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxGaDen.add(cboGaDen);

        pnlRightTop.add(boxGaDen);
        pnlRightTop.add(filler2);

        boxTau.setLayout(new javax.swing.BoxLayout(boxTau, javax.swing.BoxLayout.X_AXIS));

        lblTau.setText("Mã tàu");
        lblTau.setPreferredSize(new java.awt.Dimension(80, 0));
        boxTau.add(lblTau);

        cboTau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxTau.add(cboTau);

        pnlRightTop.add(boxTau);
        pnlRightTop.add(filler5);

        boxNgayDi.setLayout(new javax.swing.BoxLayout(boxNgayDi, javax.swing.BoxLayout.X_AXIS));

        lblNgayDi.setText("Ngày đi");
        lblNgayDi.setPreferredSize(new java.awt.Dimension(80, 0));
        boxNgayDi.add(lblNgayDi);
        boxNgayDi.add(txtNgayDi);

        pnlRightTop.add(boxNgayDi);
        pnlRightTop.add(filler6);

        boxGioDi.setLayout(new javax.swing.BoxLayout(boxGioDi, javax.swing.BoxLayout.X_AXIS));

        lblGioDi.setText("Giờ đi");
        lblGioDi.setPreferredSize(new java.awt.Dimension(80, 0));
        boxGioDi.add(lblGioDi);
        boxGioDi.add(txtGioDi);

        pnlRightTop.add(boxGioDi);
        pnlRightTop.add(filler3);

        boxNgayDen.setLayout(new javax.swing.BoxLayout(boxNgayDen, javax.swing.BoxLayout.X_AXIS));

        lblNgayDen.setText("Ngày đến");
        lblNgayDen.setPreferredSize(new java.awt.Dimension(80, 0));
        boxNgayDen.add(lblNgayDen);

        txtNgayDen.setEditable(false);
        boxNgayDen.add(txtNgayDen);

        pnlRightTop.add(boxNgayDen);
        pnlRightTop.add(filler7);

        boxGioDen.setLayout(new javax.swing.BoxLayout(boxGioDen, javax.swing.BoxLayout.X_AXIS));

        lblGioDen.setText("Giờ đến");
        lblGioDen.setPreferredSize(new java.awt.Dimension(80, 0));
        boxGioDen.add(lblGioDen);

        txtGioDen.setEditable(false);
        boxGioDen.add(txtGioDen);

        pnlRightTop.add(boxGioDen);
        pnlRightTop.add(filler4);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        boxChucNang.add(btnThem);

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        boxChucNang.add(btnCapNhat);

        pnlRightTop.add(boxChucNang);

        pnlLeft.add(pnlRightTop, java.awt.BorderLayout.NORTH);
        pnlLeft.add(jLayeredPane1, java.awt.BorderLayout.CENTER);

        add(pnlLeft, java.awt.BorderLayout.LINE_START);

        pnlRight.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pnlRight.setLayout(new java.awt.BorderLayout());

        tblChuyenTau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã chuyến", "Mác tàu", "Mã tàu", "Ga đi", "Ga đến", "Thời gian đi", "Thời gian đến"
            }
        ));
        jScrollPane1.setViewportView(tblChuyenTau);

        pnlRight.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlRightNorth.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblTimMaChuyen.setText("Mã chuyến");
        pnlRightNorth.add(lblTimMaChuyen);
        pnlRightNorth.add(filler8);

        txtTimMaChuyen.setPreferredSize(new java.awt.Dimension(150, 22));
        txtTimMaChuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimMaChuyenActionPerformed(evt);
            }
        });
        pnlRightNorth.add(txtTimMaChuyen);
        pnlRightNorth.add(filler9);

        btnTraCuuTheoMa.setText("Tra cứu theo mã");
        pnlRightNorth.add(btnTraCuuTheoMa);

        pnlRight.add(pnlRightNorth, java.awt.BorderLayout.PAGE_START);

        add(pnlRight, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void txtTimMaChuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimMaChuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimMaChuyenActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boxChucNang;
    private javax.swing.JPanel boxGaDen;
    private javax.swing.JPanel boxGaDi;
    private javax.swing.JPanel boxGioDen;
    private javax.swing.JPanel boxGioDi;
    private javax.swing.JPanel boxNgayDen;
    private javax.swing.JPanel boxNgayDi;
    private javax.swing.JPanel boxTau;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTraCuuTheoMa;
    private javax.swing.JComboBox<String> cboGaDen;
    private javax.swing.JComboBox<String> cboGaDi;
    private javax.swing.JComboBox<String> cboTau;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGaDen;
    private javax.swing.JLabel lblGaDi;
    private javax.swing.JLabel lblGioDen;
    private javax.swing.JLabel lblGioDi;
    private javax.swing.JLabel lblNgayDen;
    private javax.swing.JLabel lblNgayDi;
    private javax.swing.JLabel lblTau;
    private javax.swing.JLabel lblTimMaChuyen;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlRightNorth;
    private javax.swing.JPanel pnlRightTop;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JTable tblChuyenTau;
    private javax.swing.JTextField txtGioDen;
    private javax.swing.JTextField txtGioDi;
    private javax.swing.JTextField txtNgayDen;
    private javax.swing.JTextField txtNgayDi;
    private javax.swing.JTextField txtTimMaChuyen;
    // End of variables declaration//GEN-END:variables
}
