/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author Huy
 */
public class PnlKhuyenMai extends javax.swing.JPanel {

    /**
     * Creates new form PnlChuyenTau
     */
    public PnlKhuyenMai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlLeft = new javax.swing.JPanel();
        pnlRightTop = new javax.swing.JPanel();
        boxNgayAD = new javax.swing.JPanel();
        lblNgayAD = new javax.swing.JLabel();
        txtNgayAD = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        boxNgayKT = new javax.swing.JPanel();
        lblNgayKT = new javax.swing.JLabel();
        txtNgayKT = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        boxDoiTuong = new javax.swing.JPanel();
        lblDoiTuong = new javax.swing.JLabel();
        cboDoiTuong = new javax.swing.JComboBox<>();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        boxPhanTram = new javax.swing.JPanel();
        lblPhanTram = new javax.swing.JLabel();
        txtPhanTram = new javax.swing.JTextField();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        boxChucNang = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        pnlRight = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhuyenMai = new javax.swing.JTable();
        pnlRightNorth = new javax.swing.JPanel();
        lblTimMa = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        txtTimMa = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        btnTraCuuMa = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1920, 800));
        setLayout(new java.awt.BorderLayout());

        pnlTop.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlTop.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pnlTop.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Quản lý khuyến mãi");
        pnlTop.add(lblTitle, java.awt.BorderLayout.CENTER);

        add(pnlTop, java.awt.BorderLayout.NORTH);

        pnlLeft.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khuyến mãi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        pnlLeft.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pnlLeft.setPreferredSize(new java.awt.Dimension(300, 182));
        pnlLeft.setLayout(new java.awt.BorderLayout());

        pnlRightTop.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlRightTop.setLayout(new javax.swing.BoxLayout(pnlRightTop, javax.swing.BoxLayout.Y_AXIS));

        boxNgayAD.setLayout(new javax.swing.BoxLayout(boxNgayAD, javax.swing.BoxLayout.X_AXIS));

        lblNgayAD.setText("Ngày áp dụng");
        lblNgayAD.setPreferredSize(new java.awt.Dimension(100, 0));
        boxNgayAD.add(lblNgayAD);
        boxNgayAD.add(txtNgayAD);

        pnlRightTop.add(boxNgayAD);
        pnlRightTop.add(filler1);

        boxNgayKT.setLayout(new javax.swing.BoxLayout(boxNgayKT, javax.swing.BoxLayout.X_AXIS));

        lblNgayKT.setText("Ngày kết thúc");
        lblNgayKT.setPreferredSize(new java.awt.Dimension(100, 0));
        boxNgayKT.add(lblNgayKT);
        boxNgayKT.add(txtNgayKT);

        pnlRightTop.add(boxNgayKT);
        pnlRightTop.add(filler2);

        boxDoiTuong.setLayout(new javax.swing.BoxLayout(boxDoiTuong, javax.swing.BoxLayout.X_AXIS));

        lblDoiTuong.setText("Đối tượng");
        lblDoiTuong.setPreferredSize(new java.awt.Dimension(100, 0));
        boxDoiTuong.add(lblDoiTuong);

        cboDoiTuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxDoiTuong.add(cboDoiTuong);

        pnlRightTop.add(boxDoiTuong);
        pnlRightTop.add(filler5);

        boxPhanTram.setLayout(new javax.swing.BoxLayout(boxPhanTram, javax.swing.BoxLayout.X_AXIS));

        lblPhanTram.setText("Phần trăm");
        lblPhanTram.setPreferredSize(new java.awt.Dimension(100, 0));
        boxPhanTram.add(lblPhanTram);
        boxPhanTram.add(txtPhanTram);

        pnlRightTop.add(boxPhanTram);
        pnlRightTop.add(filler7);
        pnlRightTop.add(filler4);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        boxChucNang.add(btnThem);

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        boxChucNang.add(btnCapNhat);

        pnlRightTop.add(boxChucNang);

        pnlLeft.add(pnlRightTop, java.awt.BorderLayout.NORTH);

        add(pnlLeft, java.awt.BorderLayout.LINE_START);

        pnlRight.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pnlRight.setLayout(new java.awt.BorderLayout());

        tblKhuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã khuyến mãi", "Ngày áp dụng", "Ngày kết thúc", "Đối tượng", "Phần trăm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblKhuyenMai);

        pnlRight.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlRightNorth.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblTimMa.setText("Mã khuyến mãi");
        pnlRightNorth.add(lblTimMa);
        pnlRightNorth.add(filler6);

        txtTimMa.setPreferredSize(new java.awt.Dimension(150, 22));
        txtTimMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimMaActionPerformed(evt);
            }
        });
        pnlRightNorth.add(txtTimMa);
        pnlRightNorth.add(filler3);

        btnTraCuuMa.setText("Tra cứu theo mã");
        pnlRightNorth.add(btnTraCuuMa);

        pnlRight.add(pnlRightNorth, java.awt.BorderLayout.PAGE_START);

        add(pnlRight, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void txtTimMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimMaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boxChucNang;
    private javax.swing.JPanel boxDoiTuong;
    private javax.swing.JPanel boxNgayAD;
    private javax.swing.JPanel boxNgayKT;
    private javax.swing.JPanel boxPhanTram;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTraCuuMa;
    private javax.swing.JComboBox<String> cboDoiTuong;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDoiTuong;
    private javax.swing.JLabel lblNgayAD;
    private javax.swing.JLabel lblNgayKT;
    private javax.swing.JLabel lblPhanTram;
    private javax.swing.JLabel lblTimMa;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlRightNorth;
    private javax.swing.JPanel pnlRightTop;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JTable tblKhuyenMai;
    private javax.swing.JTextField txtNgayAD;
    private javax.swing.JTextField txtNgayKT;
    private javax.swing.JTextField txtPhanTram;
    private javax.swing.JTextField txtTimMa;
    // End of variables declaration//GEN-END:variables
}
