/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author Huy
 */
public class PnlKhachHang extends javax.swing.JPanel {

    /**
     * Creates new form PnlChuyenTau
     */
    public PnlKhachHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlLeft = new javax.swing.JPanel();
        pnlRightTop = new javax.swing.JPanel();
        boxMaKH = new javax.swing.JPanel();
        lblNgayAD = new javax.swing.JLabel();
        txtNgayAD = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        boxTenKH = new javax.swing.JPanel();
        lblNgayKT = new javax.swing.JLabel();
        txtNgayKT = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        boxCccd = new javax.swing.JPanel();
        lblDoiTuong = new javax.swing.JLabel();
        cboDoiTuong = new javax.swing.JComboBox<>();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        boxSdt = new javax.swing.JPanel();
        lblPhanTram = new javax.swing.JLabel();
        txtPhanTram = new javax.swing.JTextField();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        boxEmail = new javax.swing.JPanel();
        lblPhanTram1 = new javax.swing.JLabel();
        txtPhanTram1 = new javax.swing.JTextField();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        boxNgaySinh = new javax.swing.JPanel();
        lblPhanTram2 = new javax.swing.JLabel();
        txtPhanTram2 = new javax.swing.JTextField();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        boxDoiTuong = new javax.swing.JPanel();
        lblPhanTram3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        boxChucNang = new javax.swing.JPanel();
        btnCapNhat = new javax.swing.JButton();
        pnlRight = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhuyenMai = new javax.swing.JTable();
        pnlRightNorth = new javax.swing.JPanel();
        lblTimMa = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        txtTimMa = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        btnTraCuuMa = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1920, 800));
        setLayout(new java.awt.BorderLayout());

        pnlTop.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlTop.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pnlTop.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Quản lý khách hàng");
        pnlTop.add(lblTitle, java.awt.BorderLayout.CENTER);

        add(pnlTop, java.awt.BorderLayout.NORTH);

        pnlLeft.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khuyến mãi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        pnlLeft.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pnlLeft.setPreferredSize(new java.awt.Dimension(300, 182));
        pnlLeft.setLayout(new java.awt.BorderLayout());

        pnlRightTop.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlRightTop.setLayout(new javax.swing.BoxLayout(pnlRightTop, javax.swing.BoxLayout.Y_AXIS));

        boxMaKH.setLayout(new javax.swing.BoxLayout(boxMaKH, javax.swing.BoxLayout.X_AXIS));

        lblNgayAD.setText("Mã khách hàng");
        lblNgayAD.setPreferredSize(new java.awt.Dimension(100, 0));
        boxMaKH.add(lblNgayAD);

        txtNgayAD.setEditable(false);
        boxMaKH.add(txtNgayAD);

        pnlRightTop.add(boxMaKH);
        pnlRightTop.add(filler1);

        boxTenKH.setLayout(new javax.swing.BoxLayout(boxTenKH, javax.swing.BoxLayout.X_AXIS));

        lblNgayKT.setText("Tên khách hàng");
        lblNgayKT.setPreferredSize(new java.awt.Dimension(100, 0));
        boxTenKH.add(lblNgayKT);
        boxTenKH.add(txtNgayKT);

        pnlRightTop.add(boxTenKH);
        pnlRightTop.add(filler2);

        boxCccd.setLayout(new javax.swing.BoxLayout(boxCccd, javax.swing.BoxLayout.X_AXIS));

        lblDoiTuong.setText("CCCD");
        lblDoiTuong.setPreferredSize(new java.awt.Dimension(100, 0));
        boxCccd.add(lblDoiTuong);

        cboDoiTuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxCccd.add(cboDoiTuong);

        pnlRightTop.add(boxCccd);
        pnlRightTop.add(filler5);

        boxSdt.setLayout(new javax.swing.BoxLayout(boxSdt, javax.swing.BoxLayout.X_AXIS));

        lblPhanTram.setText("Số điện thoại");
        lblPhanTram.setPreferredSize(new java.awt.Dimension(100, 0));
        boxSdt.add(lblPhanTram);
        boxSdt.add(txtPhanTram);

        pnlRightTop.add(boxSdt);
        pnlRightTop.add(filler7);

        boxEmail.setLayout(new javax.swing.BoxLayout(boxEmail, javax.swing.BoxLayout.X_AXIS));

        lblPhanTram1.setText("Email");
        lblPhanTram1.setPreferredSize(new java.awt.Dimension(100, 0));
        boxEmail.add(lblPhanTram1);
        boxEmail.add(txtPhanTram1);

        pnlRightTop.add(boxEmail);
        pnlRightTop.add(filler8);

        boxNgaySinh.setLayout(new javax.swing.BoxLayout(boxNgaySinh, javax.swing.BoxLayout.X_AXIS));

        lblPhanTram2.setText("Ngày sinh");
        lblPhanTram2.setPreferredSize(new java.awt.Dimension(100, 0));
        boxNgaySinh.add(lblPhanTram2);
        boxNgaySinh.add(txtPhanTram2);

        pnlRightTop.add(boxNgaySinh);
        pnlRightTop.add(filler4);

        boxDoiTuong.setLayout(new javax.swing.BoxLayout(boxDoiTuong, javax.swing.BoxLayout.X_AXIS));

        lblPhanTram3.setText("Đối tượng");
        lblPhanTram3.setPreferredSize(new java.awt.Dimension(100, 0));
        boxDoiTuong.add(lblPhanTram3);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxDoiTuong.add(jComboBox1);

        pnlRightTop.add(boxDoiTuong);
        pnlRightTop.add(filler9);
        pnlRightTop.add(filler10);

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        boxChucNang.add(btnCapNhat);

        pnlRightTop.add(boxChucNang);

        pnlLeft.add(pnlRightTop, java.awt.BorderLayout.NORTH);

        add(pnlLeft, java.awt.BorderLayout.LINE_START);

        pnlRight.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pnlRight.setLayout(new java.awt.BorderLayout());

        tblKhuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã khuyến mãi", "Ngày áp dụng", "Ngày kết thúc", "Đối tượng", "Phần trăm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblKhuyenMai);

        pnlRight.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlRightNorth.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblTimMa.setText("Mã khách hàng");
        pnlRightNorth.add(lblTimMa);
        pnlRightNorth.add(filler6);

        txtTimMa.setPreferredSize(new java.awt.Dimension(150, 22));
        txtTimMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimMaActionPerformed(evt);
            }
        });
        pnlRightNorth.add(txtTimMa);
        pnlRightNorth.add(filler3);

        btnTraCuuMa.setText("Tra cứu theo mã");
        pnlRightNorth.add(btnTraCuuMa);

        pnlRight.add(pnlRightNorth, java.awt.BorderLayout.PAGE_START);

        add(pnlRight, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void txtTimMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimMaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boxCccd;
    private javax.swing.JPanel boxChucNang;
    private javax.swing.JPanel boxDoiTuong;
    private javax.swing.JPanel boxEmail;
    private javax.swing.JPanel boxMaKH;
    private javax.swing.JPanel boxNgaySinh;
    private javax.swing.JPanel boxSdt;
    private javax.swing.JPanel boxTenKH;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnTraCuuMa;
    private javax.swing.JComboBox<String> cboDoiTuong;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDoiTuong;
    private javax.swing.JLabel lblNgayAD;
    private javax.swing.JLabel lblNgayKT;
    private javax.swing.JLabel lblPhanTram;
    private javax.swing.JLabel lblPhanTram1;
    private javax.swing.JLabel lblPhanTram2;
    private javax.swing.JLabel lblPhanTram3;
    private javax.swing.JLabel lblTimMa;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlRightNorth;
    private javax.swing.JPanel pnlRightTop;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JTable tblKhuyenMai;
    private javax.swing.JTextField txtNgayAD;
    private javax.swing.JTextField txtNgayKT;
    private javax.swing.JTextField txtPhanTram;
    private javax.swing.JTextField txtPhanTram1;
    private javax.swing.JTextField txtPhanTram2;
    private javax.swing.JTextField txtTimMa;
    // End of variables declaration//GEN-END:variables
}
